--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG



--TAO BANG HD_BANSP
CREATE TABLE HD_BANSP(
    SoHD CHAR(5) NOT NULL PRIMARY KEY,
    MaKH CHAR(5),
    MaPBH CHAR(5),
    MaNV CHAR(5),
    NgayLapHD DATE,
    TriGia NUMBER
);



-------------TAO KHOA NGOAI
ALTER TABLE HD_BANSP  ADD CONSTRAINT FK_HD_PBH FOREIGN KEY (MAPBH) REFERENCES PHIEUBAOHANH(MAPBH);
ALTER TABLE HD_BANSP  ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE HD_BANSP  ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

