--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG


--TAO BANG KHACHHANG
CREATE TABLE KHACHHANG(
    MaKH CHAR(5) NOT NULL PRIMARY KEY,
    TenKH VARCHAR2(30),
    DiaChi VARCHAR2(100),
    CMND VARCHAR2(12),
    Email VARCHAR2(50),
    SDT VARCHAR2(10)
);


