--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG


--TAO BANG KHUYENMAI
CREATE TABLE KHUYENMAI(
    MaKM CHAR(5) NOT NULL PRIMARY KEY,
    TenKM VARCHAR2(25),
    NgayBD DATE,
    NgayKT DATE,
    PhanTramKM NUMBER
);



