--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG


--TAO BANG PHONGBAN
CREATE TABLE PHONGBAN(
    MaPB CHAR(5) NOT NULL PRIMARY KEY,
    TenPB VARCHAR2(30),
    SoLuongNV NUMBER,
    TruongPB CHAR(5)
);



