--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG

--TAO BANG CHI TIET HOA DON
CREATE TABLE CTHD_BANSP(
    SoHD CHAR(5),
    MaSP CHAR(5),
    SoLuong NUMBER,
    CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP)
);


-------------TAO KHOA NGOAI
ALTER TABLE CTHD_BANSP  ADD CONSTRAINT FK_CTHD FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE CTHD_BANSP  ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HD_BANSP(SOHD);
