--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG


--TAO BANG DANGNHAP
CREATE TABLE DANGNHAP(
    TenDN VARCHAR2(20) NOT NULL PRIMARY KEY,
    CapBac VARCHAR2(20),
    MatKhau VARCHAR2(20),
    MaNV CHAR(5)
);


-------------TAO KHOA NGOAI
ALTER TABLE DANGNHAP ADD CONSTRAINT FK_NVDN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
