--DATABASE QUAN LY CUA HANG DIEN THOAI DI DONG

--TAO BANG NHACUNGCAP 
CREATE TABLE NHACUNGCAP(
    MaNCC CHAR(5) NOT NULL PRIMARY KEY,
    TenNCC VARCHAR2(100),
    DiaChi VARCHAR2(100),
    Email VARCHAR2(50),
    SDT VARCHAR2(10)
);


